cc_binary(
    name = "submit",
    deps = [],
    srcs = [
        "submit.cpp",
    ],
    defines = [
        "SUBMIT_LIST=STR(Makefile),STR(proj1.c),STR(proj1.h)",
        "TARGET_DIR=/c/cs323/proj1/.submit",
        "GET_DIR_PREFIX=/home/accts",
    ],
)
